#!/bin/bash

while true
do
read -r -p "Do you want to create a new user? Y or N or Q (to quit): " ans

case "$ans" in
Y|y)
read -r -p "Enter username: " username
sudo useradd -m "$username" &&
#sudo passwd "$username" &&
echo "$username:$username@123" | sudo chpasswd &&
sudo chage -d 0 "$username" &&
id "$username" &&
getent passwd "$username" &&
echo "New user added: $username" ||
echo "User creation failed: $username"
;;

N|n)
echo "Stopping..."
;;

Q|q)
echo "Goodbye!"
break
;;

*)
echo "Invalid output" >&2
;;

esac
done
